DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cinema_migrator') THEN
CREATE ROLE cinema_migrator LOGIN PASSWORD 'migrator' CREATEDB;
END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cinema_app') THEN
CREATE ROLE cinema_app LOGIN PASSWORD 'app';
END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cinema_ro') THEN
CREATE ROLE cinema_ro LOGIN PASSWORD 'readonly';
END IF;
END $$;

GRANT USAGE ON SCHEMA public TO cinema_app, cinema_ro;
GRANT USAGE, CREATE ON SCHEMA public TO cinema_migrator;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cinema_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON TABLES TO cinema_ro;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO cinema_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO cinema_ro;
