CREATE
EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE viewing
    ADD COLUMN IF NOT EXISTS session_id UUID NOT NULL DEFAULT gen_random_uuid(),
    ADD COLUMN IF NOT EXISTS tags TEXT[] NULL,
    ADD COLUMN IF NOT EXISTS meta JSONB NULL,
    ADD COLUMN IF NOT EXISTS geo POINT NULL;

ALTER TABLE purchase
    ADD COLUMN IF NOT EXISTS coupon_code TEXT NULL,
    ADD COLUMN IF NOT EXISTS payment_meta JSONB NULL,
    ADD COLUMN IF NOT EXISTS amount_range INT4RANGE NULL;

ALTER TABLE rental
    ADD COLUMN IF NOT EXISTS rental_period TSTZRANGE NULL,
    ADD COLUMN IF NOT EXISTS notes TEXT NULL;

ALTER TABLE review
    ADD COLUMN IF NOT EXISTS sentiment SMALLINT NULL,
    ADD COLUMN IF NOT EXISTS comment_tsv TSVECTOR
    GENERATED ALWAYS AS (to_tsvector('simple', coalesce (comment,''))) STORED;
